// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"login","path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/my-profile","name":"My Profile","icon":"./icons/icon_memo.svg","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"Challenge","icon":"./icons/icon_challenge.svg","path":"/Challenge","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"Info","icon":"./icons/icon_info.svg","path":"/infomation","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/","redirect":"/my-profile","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"*","layout":false,"id":"7"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}},
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__MyProfile__index" */'@/pages/MyProfile/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__TableList__index" */'@/pages/TableList/index.tsx')),
'6': React.lazy(() => import( './EmptyRoute')),
'7': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/phanthanhbinh/Project/arent-test-website/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'/Users/phanthanhbinh/Project/arent-test-website/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
